#!/usr/bin/env python3
"""
Generate Test Parameters for Demographic Simulation

This script generates test parameters for immigration, fertility, and death rates.
The fertility parameters are now generated by reading the AESFR_matrix_combine.bin file,
which contains real fertility rate data from the C++ demographic simulation.

Key Features:
- Reads binary fertility data from AESFR_matrix_combine.bin
- Applies the same fertility logic as the C++ fertility.cpp implementation
- Generates realistic fertility parameters based on age, ethnicity, and year
- Includes validation and testing functions
- Exports sample data for inspection

File Structure:
- AESFR_matrix_combine.bin: Binary file with fertility rates [12][71][35]
  - 12 ethnicities (including gender variations)
  - 71 time periods (1980-2050)
  - 35 age groups (15-49 years)

Usage:
    python generate_test_params.py
    
    # Test fertility reading only:
    python test_fertility_reading.py

Dependencies:
    - pandas
    - numpy
    - struct (built-in)
    - os (built-in)

Author: Modified to integrate with C++ demographic simulation
"""

import itertools
import json
import struct
import numpy as np
import pandas as pd
import os

GENDERS = ['male', 'female']
RACES = ['chinese', 'malay', 'indian', 'other']

START_YEAR = 2024
END_YEAR = 2030
SIM_YEARS = np.arange(START_YEAR, 1 + END_YEAR)
AGES = np.arange(85 + 1)

# Constants from C++ code
FER_MAT_SIZE = 12 * 71 * 35  # 12 ethnicities, 71 time periods, 35 age groups
CHILDBEARING_START_AGE = 15
CHILDBEARING_END_AGE = 49

def read_aesfr_binary_file(filepath):
    """
    Read the AESFR_matrix_combine.bin file and return the fertility rates matrix.
    
    The file contains double precision data in format [12][71][35]:
    - 12 ethnicities (including gender variations)
    - 71 time periods (1980-2050)
    - 35 age groups (15-49)
    """
    if not os.path.exists(filepath):
        print(f"Warning: {filepath} not found. Using default fertility rates.")
        return None
    
    try:
        with open(filepath, 'rb') as file:
            # Read double precision data
            data = file.read(FER_MAT_SIZE * 8)  # 8 bytes per double
            if len(data) != FER_MAT_SIZE * 8:
                print(f"Warning: Expected {FER_MAT_SIZE * 8} bytes, got {len(data)}")
                return None
            
            # Convert to double array
            double_array = struct.unpack('d' * FER_MAT_SIZE, data)
            
            # Reshape to 3D array [12][71][35] (ethnicities, time periods, age groups)
            fertility_matrix = np.array(double_array).reshape(12, 71, 35)
            
            print(f"Successfully loaded fertility matrix: {fertility_matrix.shape}")
            
            # Debug: Check if different ethnicities have different data
            print("\nDebug: Checking data uniqueness across ethnicities:")
            for eth in range(0, 4):
                first_values = fertility_matrix[eth, 0, 0:5]
                print(f"Ethnicity {eth} first values: {first_values}")
            
            # Check if the issue might be with the reshape
            print(f"\nDebug: Raw array stats - min: {np.array(double_array).min():.6f}, max: {np.array(double_array).max():.6f}")
            
            return fertility_matrix
            
    except Exception as e:
        print(f"Error reading {filepath}: {e}")
        return None

def map_fertility_rate(fertility_matrix, ethnicity_idx, year_idx, age):
    """
    Map fertility rate from the matrix, following the C++ logic from fertility.cpp.
    
    Args:
        fertility_matrix: 3D array [12][71][35] (ethnicities, time periods, age groups)
        - 12 ethnicities (including gender variations)
        - 71 time periods (1980-2050) 
        - 35 age groups (15-49)
        ethnicity_idx: ethnicity index (1,3,5,7) where:
            - 1: Chinese female -> matrix_idx 0
            - 3: Malay female -> matrix_idx 1  
            - 5: Indian female -> matrix_idx 2
            - 7: Other female -> matrix_idx 3
        year_idx: year index relative to 1990
        age: age of the person
    
    Returns:
        fertility rate for the given parameters
    """
    if age < CHILDBEARING_START_AGE or age > CHILDBEARING_END_AGE:
        return 0.0
    
    # Convert ethnicity index to matrix index (similar to C++ index/2 logic)
    # This maps: 1->0 (Chinese), 3->1 (Malay), 5->2 (Indian), 7->3 (Other)
    matrix_idx = ethnicity_idx // 2 
    # Map year index (C++ logic: year_idx + 10)
    matrix_year_idx = year_idx + 10
    
    # Map age (C++ logic: age - 15)
    matrix_age_idx = age - CHILDBEARING_START_AGE
    
    
    # Bounds checking
    if (matrix_year_idx < 0 or matrix_year_idx >= 71 or 
        matrix_age_idx < 0 or matrix_age_idx >= 35 or
        matrix_idx >= 12):
        return 0.0
    
    # Access as [ethnicity][time][age] since matrix is [12][71][35]
    return float(fertility_matrix[matrix_idx, matrix_year_idx, matrix_age_idx])

def print_fertility_matrix(fertility_matrix):
    """
    Print basic information about the fertility matrix.
    """
    if fertility_matrix is None:
        print("No fertility matrix to display")
        return
    
    print(f"Matrix shape: {fertility_matrix.shape}")
    
    # Print a sample slice for inspection
    print("\nSample fertility rates [ethnicity][years 1990-2000][ages 25-45]:")
    print("Shape of sample slice:", fertility_matrix[:, 10:20, 10:30].shape)
    
    # Compare specific ethnicities
    print("\nComparing Chinese female (1) vs Malay female (3):")
    chinese_female = fertility_matrix[1, 10:20, 10:30]
    malay_female = fertility_matrix[3, 10:20, 10:30]
    print(f"Chinese female values: {chinese_female}")
    print(f"Malay female values: {malay_female}")
    print(f"Are they identical? {np.array_equal(chinese_female, malay_female)}")
    
    # Check if the issue is with the binary file reading
    print("\nChecking first few values of each ethnicity:")
    print("Note: eth 0,1,2,3 corresponds to Chinese, Malay, Indian, Others (via map_fertility_rate function)")
    for eth in range(0, 4):
        first_values = fertility_matrix[eth, 0, 0:5]
        print(f"Ethnicity {eth} [0, 0:5]: {first_values}")
    
    # Check the last 10 values of each ethnicity as well
    print("\nChecking last 10 values of each ethnicity:")
    for eth in range(0, 4):
        last_values = fertility_matrix[eth, -1, -10:]
        print(f"Ethnicity {eth} [-1, -10:]: {last_values}")
    
    # Verify the mapping is correct
    print("\nVerifying ethnicity mapping:")
    print("Chinese female (race_idx=1) -> matrix_idx=0: ", fertility_matrix[0, 0, 0:5])
    print("Malay female (race_idx=3) -> matrix_idx=1: ", fertility_matrix[1, 0, 0:5])
    print("Indian female (race_idx=5) -> matrix_idx=2: ", fertility_matrix[2, 0, 0:5])
    print("Other female (race_idx=7) -> matrix_idx=3: ", fertility_matrix[3, 0, 0:5])

def export_fertility_matrix_to_csv(fertility_matrix, output_path="fertility_matrix_sample.csv"):
    """
    Export a sample of the fertility matrix to CSV for inspection.
    This helps verify the data structure and values.
    """
    if fertility_matrix is None:
        print("No fertility matrix to export")
        return
    
    try:
        # Create a sample dataframe with key fertility rates
        sample_data = []
        years = [1980, 1990, 2000, 2010, 2020, 2030, 2040, 2050]
        ages = [15, 20, 25, 30, 35, 40, 45]
        ethnicities = ['chinese_male', 'chinese_female', 'malay_male', 'malay_female', 
                      'indian_male', 'indian_female', 'other_male', 'other_female']
        
        for year in years:
            year_idx = year - 1990
            if year_idx > fertility_matrix.shape[1]:  # Check bounds for years
                raise ValueError(f"Year {year} is out of bounds")
            for age in ages:
                age_idx = age - 15
                if age_idx > fertility_matrix.shape[2]:  # Check bounds for ages
                    raise ValueError(f"Age {age} is out of bounds")
                for eth_idx, ethnicity in enumerate(ethnicities):
                    if eth_idx % 2 == 1:  # Only females
                        # Access as [ethnicity][time][age]
                        print(f"eth_idx: {eth_idx}, year_idx: {year_idx}, age_idx: {age_idx}")
                        # Map ethnicity index to race_idx for mapping function
                        
                        race_idx = eth_idx
                        rate = map_fertility_rate(fertility_matrix, race_idx, year_idx, age)
                        sample_data.append({
                            'year': year,
                            'age': age,
                            'ethnicity': ethnicity,
                            'fertility_rate': rate
                        })
        
        sample_df = pd.DataFrame(sample_data)
        sample_df.to_csv(output_path, index=False)
        print(f"Fertility matrix sample exported to {output_path}")
        
        # Also show a summary table
        print("\nFertility Matrix Summary (sample values):")
        pivot_df = sample_df.pivot_table(
            values='fertility_rate', 
            index=['year', 'age'], 
            columns='ethnicity', 
            aggfunc='first'  # Use 'first' to handle any duplicate entries by taking the first occurrence
        )
        # Maintain the original order (Chinese, Malay, Indian, Other)
        desired_order = ['chinese_female', 'malay_female', 'indian_female', 'other_female']
        pivot_df = pivot_df.reindex(columns=desired_order)
        print(pivot_df.round(4))
        
    except Exception as e:
        print(f"Error exporting fertility matrix: {e}")

def test_fertility_mapping(fertility_matrix):
    """
    Test the fertility rate mapping logic to ensure it produces reasonable results.
    """
    if fertility_matrix is None:
        print("No fertility matrix to test")
        return
    
    print("\nTesting Fertility Rate Mapping Logic:")
    print("=" * 50)
    
    # Test cases based on the C++ logic
    test_cases = []
    years = range(1990, 2015)  # 2024-2030
    races = ['chinese', 'malay', 'indian', 'other']
    ages = range(15, 26)  # 15-25
    
    for year in years:
        for race in races:
            for age in ages:
                test_cases.append({
                    'year': year,
                    'age': age,
                    'race': race,
                    'expected_range': (0.0, 1.0)
                })
    
    race_to_idx = {'chinese': 1, 'malay': 3, 'indian': 5, 'other': 7}  # Female indices
    # These will be converted by map_fertility_rate: 1->0, 3->1, 5->2, 7->3
    
    for test_case in test_cases:
        year = test_case['year']
        age = test_case['age']
        race = test_case['race']
        expected_min, expected_max = test_case['expected_range']
        
        race_idx = race_to_idx.get(race, 0)
        year_idx = year - 1990
        rate = map_fertility_rate(fertility_matrix, race_idx, year_idx, age)
        
        # Check if rate is within expected range
        is_valid = expected_min <= rate <= expected_max
        
        status = "✓" if is_valid else "✗"
        print(f"{status} {race.capitalize()}, year {year}, age {age}: {rate:.6f}")
        
        if not is_valid:
            print(f"    Warning: Rate {rate:.6f} outside expected range [{expected_min}, {expected_max}]")
    
    print("\nFertility Rate Mapping Test Complete")

def generate_fertility_params() -> pd.DataFrame:
    """
    Generate fertility parameters by reading the AESFR_matrix_combine.bin file
    and applying the fertility logic from fertility.cpp.
    """
    # Try to read the binary file (relative to project root)
    binary_filepath = "../data/bin/AESFR_matrix_combine.bin"
    fertility_matrix = read_aesfr_binary_file(binary_filepath)
    
    # Print matrix information
    if fertility_matrix is not None:
        print_fertility_matrix(fertility_matrix)
        
        # Test the mapping logic
        test_fertility_mapping(fertility_matrix)
        
        # Export sample for inspection
        export_fertility_matrix_to_csv(fertility_matrix)
    
    # Create the base dataframe
    df = pd.DataFrame(
        itertools.product(SIM_YEARS, RACES, AGES),
        columns=['sim_year', 'agent_race', 'agent_age'],
    )
    
    if fertility_matrix is not None:
        # Use real fertility rates from the binary file
        print("Using fertility rates from AESFR_matrix_combine.bin")
        
        # Map race names to indices (assuming order matches the C++ code)
        # Based on the C++ code, the mapping seems to be:
        # 0: Chinese male, 1: Chinese female, 2: Malay male, 3: Malay female, etc.
        # We use female indices for fertility calculations
        # The map_fertility_rate function will convert these to matrix indices:
        # 1 (Chinese) -> 0, 3 (Malay) -> 1, 5 (Indian) -> 2, 7 (Other) -> 3
        race_to_idx = {'chinese': 1, 'malay': 3, 'indian': 5, 'other': 7}
        
        def get_fertility_rate(row):
            
            race_idx = race_to_idx.get(row['agent_race'], 0)

            year_idx = row['sim_year'] - 1990  # Convert to relative year index
            age = row['agent_age']
            
            return map_fertility_rate(fertility_matrix, race_idx, year_idx, age)
        
        df['birth_prob'] = df.apply(get_fertility_rate, axis=1)
        
        # Set fertility to 0 for ages outside childbearing range
        age_mask = (df['agent_age'] < CHILDBEARING_START_AGE) | (df['agent_age'] > CHILDBEARING_END_AGE)
        df.loc[age_mask, 'birth_prob'] = 0.0
        
        print(f"Fertility parameters generated successfully.")
        print(f"  Total rows: {len(df)}")
        print(f"  Non-zero birth probabilities: {np.count_nonzero(df['birth_prob'])}")
        print(f"  Birth probability range: {df['birth_prob'].min():.6f} - {df['birth_prob'].max():.6f}")
        
        # Show sample fertility rates for different ages and ethnicities
        sample_ages = [20, 25, 30, 35, 40]
        print(f"\nSample fertility rates for year {START_YEAR}:")
        for age in sample_ages:
            for race in RACES:
                rate = df[(df['sim_year'] == START_YEAR) & 
                         (df['agent_race'] == race) & 
                         (df['agent_age'] == age)]['birth_prob'].iloc[0]
                print(f"  {race.capitalize()}, age {age}: {rate:.6f}")
        
    else:
        # Fallback to default values if binary file not found
        print("Using default fertility rates (fallback)")
        df['birth_prob'] = 0.0
        age_in_range = (df['agent_age'] > 14) & (df['agent_age'] < 50)
        df.loc[age_in_range, 'birth_prob'] = 0.5
    
    return df


def generate_immigration_params() -> pd.DataFrame:
    df = pd.DataFrame(
        itertools.product(SIM_YEARS, GENDERS, RACES, AGES),
        columns=['sim_year', 'gender', 'race', 'migrant_age'],
    )
    df['migrant_count'] = 0
    df.loc[df['migrant_age'] == 30, 'migrant_count'] = 1
    return df


def generate_death_params() -> pd.DataFrame:
    df = pd.DataFrame(
        itertools.product(SIM_YEARS, GENDERS, AGES),
        columns=['sim_year', 'agent_gender', 'agent_age'],
    )
    df['agent_death_prob'] = 0.1
    return df


def main():
    diseases_dir = 'diseases'
    sim_params_path = 'tests/sim_params.json'
    immigration_params_path = 'tests/immigration_params.csv'
    fertility_params_path = 'tests/fertility_params.csv'
    death_params_path = 'tests/death_params.csv'
    output_dir = "tests/generated_output"

    generate_immigration_params().to_csv(immigration_params_path, index=False)
    generate_fertility_params().to_csv(fertility_params_path, index=False)
    generate_death_params().to_csv(death_params_path, index=False)

    sim_params = {
        "initial_population_size": 20,
        "start_time": START_YEAR,
        "end_time": END_YEAR,
        "seed": 0,
        "immigration_params": immigration_params_path,
        "fertility_params": fertility_params_path,
        "diseases": [
            {
                "name": "bmi",
                "params_path": f"{diseases_dir}/bmi/bmi_params.json",
                "output_dir": output_dir,
            },
            {
                "name": "atrial_fibrillation",
                "params_path": f"{diseases_dir}/atrial_fibrillation/atrial_fibrillation_probs.csv",
                "output_dir": output_dir,
            },
            {
                "name": "diabetes",
                "output_dir": output_dir,
            },
            {
                "name": "death",
                "params_path": death_params_path,
                "output_dir": output_dir,
            },
        ],
        "output_dir": output_dir,
    }
    with open(sim_params_path, 'w') as f:
        f.write(json.dumps(sim_params, indent=4))


if __name__ == '__main__':
    main()
